### ISSUE TITLE
Bundle products on cart are breaking the estimate shipping process

### ISSUE THREAD

**Issue by asalgado0391** [ShipHawk/shiphawk-magento-2#10]
Hi,
I'm getting this error message when generating the shipping rates for a cart with a bundle product that contains simple and configurable products:
"Fatal Error: 'Uncaught Error: Call to a member function getProduct() on null"

It seems like the problem is on the line: 213 in file Shiphawk/Shipping/Model/Carrier.php
if ($option = $item->getOptionByCode('simple_product')->getProduct()) {

**Comment by RonakParmar** [comment]
@asalgado0391  Have you fixed this issue? I am also getting the same error for the bundle product. if yes, can you please share it?
