### ISSUE TITLE
Bundle products on cart are breaking the estimate shipping process #10

### ISSUE THREAD

**Issue by RonakParmar** [ShipHawk/shiphawk-magento-2#19]
Hi,
I'm getting this error message when generating the shipping rates for a cart with a bundle product that contains simple and configurable products:
"Fatal Error: 'Uncaught Error: Call to a member function getProduct() on null"

It seems like the problem is on the line: 213 in file Shiphawk/Shipping/Model/Carrier.php
if ($option = $item->getOptionByCode('simple_product')->getProduct()) {

**Comment by Gankster** [comment]
Hi! 
Thank you for writing about the issue. We'll check and fix it ASAP.

**Comment by Gankster** [comment]
Fixed here: https://github.com/ShipHawk/shiphawk-magento-2/pull/21
